In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\rajan\Downloads\occupancy_data\datatest.txt")

In [12]:
data

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
140,2015-02-02 14:19:00,23.700000,26.272000,585.200000,749.200000,0.004764,1
141,2015-02-02 14:19:59,23.718000,26.290000,578.400000,760.400000,0.004773,1
142,2015-02-02 14:21:00,23.730000,26.230000,572.666667,769.666667,0.004765,1
143,2015-02-02 14:22:00,23.722500,26.125000,493.750000,774.750000,0.004744,1
144,2015-02-02 14:23:00,23.754000,26.200000,488.600000,779.000000,0.004767,1
...,...,...,...,...,...,...,...
2800,2015-02-04 10:38:59,24.290000,25.700000,808.000000,1150.250000,0.004829,1
2801,2015-02-04 10:40:00,24.330000,25.736000,809.800000,1129.200000,0.004848,1
2802,2015-02-04 10:40:59,24.330000,25.700000,817.000000,1125.800000,0.004841,1
2803,2015-02-04 10:41:59,24.356667,25.700000,813.000000,1123.000000,0.004849,1
2804,2015-02-04 10:43:00,24.408333,25.681667,798.000000,1124.000000,0.004860,1

In [3]:
data.describe()

,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
count,2665.000000,2665.000000,2665.000000,2665.000000,2665.000000,2665.000000
mean,21.433876,25.353937,193.227556,717.906470,0.004027,0.364728
std,1.028024,2.436842,250.210906,292.681718,0.000611,0.481444
min,20.200000,22.100000,0.000000,427.500000,0.003303,0.000000
25%,20.650000,23.260000,0.000000,466.000000,0.003529,0.000000
50%,20.890000,25.000000,0.000000,580.500000,0.003815,0.000000
75%,22.356667,26.856667,442.500000,956.333333,0.004532,1.000000
max,24.408333,31.472500,1697.250000,1402.250000,0.005378,1.000000

In [4]:
#Printing top records from dataframe
data.head()

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
140,2015-02-02 14:19:00,23.7000,26.272,585.200000,749.200000,0.004764,1
141,2015-02-02 14:19:59,23.7180,26.290,578.400000,760.400000,0.004773,1
142,2015-02-02 14:21:00,23.7300,26.230,572.666667,769.666667,0.004765,1
143,2015-02-02 14:22:00,23.7225,26.125,493.750000,774.750000,0.004744,1
144,2015-02-02 14:23:00,23.7540,26.200,488.600000,779.000000,0.004767,1

In [6]:
df=data.iloc[:, 1:7]

In [7]:
df = df.astype('float32')

In [8]:
df.head()

     Temperature   Humidity       Light         CO2  HumidityRatio  Occupancy
140    23.700001  26.271999  585.200012  749.200012       0.004764        1.0
141    23.718000  26.290001  578.400024  760.400024       0.004773        1.0
142    23.730000  26.230000  572.666687  769.666687       0.004765        1.0
143    23.722500  26.125000  493.750000  774.750000       0.004744        1.0
144    23.754000  26.200001  488.600006  779.000000       0.004767        1.0

In [9]:
df=df.to_numpy()

In [10]:
df.shape

(2665, 6)

In [86]:
training = df[0:1333]
testing = df[1332:]

In [87]:
print(training.shape)
print(testing.shape)

(1333, 6)
(1333, 6)

In [88]:
training_features = training[:,0:-1]
training_labels = training[:,-1]
testing_features = testing[:,0:-1]
testing_labels = testing[:,-1]

In [89]:
print(training_features.shape)
print(testing_features.shape)

(1333, 5)
(1333, 5)

In [90]:
training_features[0].shape

(5,)

In [91]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout

In [96]:
model = Sequential()
model.add(Input(shape=(5,)))
model.add(Dense(1,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(8,activation='relu'))
model.add(Dropout(0))
model.add(Dense(1, activation="softmax"))

In [97]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [98]:
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_43 (Dense)            (None, 1)                 6

 dropout_29 (Dropout)        (None, 1)                 0

 dense_44 (Dense)            (None, 8)                 16

 dropout_30 (Dropout)        (None, 8)                 0

 dense_45 (Dense)            (None, 1)                 9

=================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________

In [99]:
model.fit(training_features,training_labels,epochs=100,validation_data=(testing_features,testing_labels))

Epoch 1/100
42/42 [==============================] - 2s 11ms/step - loss: 0.4125 - accuracy: 0.3668 - val_loss: 0.2565 - val_accuracy: 0.3631
Epoch 2/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3474 - accuracy: 0.3668 - val_loss: 0.2493 - val_accuracy: 0.3631
Epoch 3/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3335 - accuracy: 0.3668 - val_loss: 0.2422 - val_accuracy: 0.3631
Epoch 4/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3309 - accuracy: 0.3668 - val_loss: 0.2356 - val_accuracy: 0.3631
Epoch 5/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3445 - accuracy: 0.3668 - val_loss: 0.2303 - val_accuracy: 0.3631
Epoch 6/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3406 - accuracy: 0.3668 - val_loss: 0.2253 - val_accuracy: 0.3631
Epoch 7/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3244 - accuracy: 0.3668 - val_loss: 0.2201 - val_accuracy: 0.3631
Epoch 8/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3383 - accuracy: 0.3668 - val_loss: 0.2160 - val_accuracy: 0.3631
Epoch 9/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3149 - accuracy: 0.3668 - val_loss: 0.2114 - val_accuracy: 0.3631
Epoch 10/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3365 - accuracy: 0.3668 - val_loss: 0.2079 - val_accuracy: 0.3631
Epoch 11/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3290 - accuracy: 0.3668 - val_loss: 0.2045 - val_accuracy: 0.3631
Epoch 12/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3166 - accuracy: 0.3668 - val_loss: 0.2009 - val_accuracy: 0.3631
Epoch 13/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3094 - accuracy: 0.3668 - val_loss: 0.1973 - val_accuracy: 0.3631
Epoch 14/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3170 - accuracy: 0.3668 - val_loss: 0.1942 - val_accuracy: 0.3631
Epoch 15/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3172 - accuracy: 0.3668 - val_loss: 0.1914 - val_accuracy: 0.3631
Epoch 16/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3096 - accuracy: 0.3668 - val_loss: 0.1885 - val_accuracy: 0.3631
Epoch 17/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3099 - accuracy: 0.3668 - val_loss: 0.1860 - val_accuracy: 0.3631
Epoch 18/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3224 - accuracy: 0.3668 - val_loss: 0.1839 - val_accuracy: 0.3631
Epoch 19/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3248 - accuracy: 0.3668 - val_loss: 0.1821 - val_accuracy: 0.3631
Epoch 20/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3060 - accuracy: 0.3668 - val_loss: 0.1799 - val_accuracy: 0.3631
Epoch 21/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3299 - accuracy: 0.3668 - val_loss: 0.1784 - val_accuracy: 0.3631
Epoch 22/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3086 - accuracy: 0.3668 - val_loss: 0.1765 - val_accuracy: 0.3631
Epoch 23/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3135 - accuracy: 0.3668 - val_loss: 0.1749 - val_accuracy: 0.3631
Epoch 24/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3171 - accuracy: 0.3668 - val_loss: 0.1735 - val_accuracy: 0.3631
Epoch 25/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3127 - accuracy: 0.3668 - val_loss: 0.1720 - val_accuracy: 0.3631
Epoch 26/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3180 - accuracy: 0.3668 - val_loss: 0.1708 - val_accuracy: 0.3631
Epoch 27/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2974 - accuracy: 0.3668 - val_loss: 0.1691 - val_accuracy: 0.3631
Epoch 28/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3108 - accuracy: 0.3668 - val_loss: 0.1678 - val_accuracy: 0.3631
Epoch 29/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3081 - accuracy: 0.3668 - val_loss: 0.1665 - val_accuracy: 0.3631
Epoch 30/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3119 - accuracy: 0.3668 - val_loss: 0.1654 - val_accuracy: 0.3631
Epoch 31/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3000 - accuracy: 0.3668 - val_loss: 0.1641 - val_accuracy: 0.3631
Epoch 32/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3039 - accuracy: 0.3668 - val_loss: 0.1630 - val_accuracy: 0.3631
Epoch 33/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3138 - accuracy: 0.3668 - val_loss: 0.1622 - val_accuracy: 0.3631
Epoch 34/100
42/42 [==============================] - 0s 2ms/step - loss: 0.3145 - accuracy: 0.3668 - val_loss: 0.1614 - val_accuracy: 0.3631
Epoch 35/100
42/42 [==============================] - 0s 2ms/step - loss: 0.3161 - accuracy: 0.3668 - val_loss: 0.1608 - val_accuracy: 0.3631
Epoch 36/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2903 - accuracy: 0.3668 - val_loss: 0.1595 - val_accuracy: 0.3631
Epoch 37/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3021 - accuracy: 0.3668 - val_loss: 0.1585 - val_accuracy: 0.3631
Epoch 38/100
42/42 [==============================] - 0s 2ms/step - loss: 0.3105 - accuracy: 0.3668 - val_loss: 0.1579 - val_accuracy: 0.3631
Epoch 39/100
42/42 [==============================] - 0s 2ms/step - loss: 0.3165 - accuracy: 0.3668 - val_loss: 0.1575 - val_accuracy: 0.3631
Epoch 40/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3043 - accuracy: 0.3668 - val_loss: 0.1568 - val_accuracy: 0.3631
Epoch 41/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3085 - accuracy: 0.3668 - val_loss: 0.1563 - val_accuracy: 0.3631
Epoch 42/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3137 - accuracy: 0.3668 - val_loss: 0.1559 - val_accuracy: 0.3631
Epoch 43/100
42/42 [==============================] - 0s 4ms/step - loss: 0.2979 - accuracy: 0.3668 - val_loss: 0.1551 - val_accuracy: 0.3631
Epoch 44/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2960 - accuracy: 0.3668 - val_loss: 0.1543 - val_accuracy: 0.3631
Epoch 45/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2985 - accuracy: 0.3668 - val_loss: 0.1535 - val_accuracy: 0.3631
Epoch 46/100
42/42 [==============================] - 0s 5ms/step - loss: 0.3206 - accuracy: 0.3668 - val_loss: 0.1534 - val_accuracy: 0.3631
Epoch 47/100
42/42 [==============================] - 0s 5ms/step - loss: 0.3126 - accuracy: 0.3668 - val_loss: 0.1531 - val_accuracy: 0.3631
Epoch 48/100
42/42 [==============================] - 0s 4ms/step - loss: 0.2885 - accuracy: 0.3668 - val_loss: 0.1522 - val_accuracy: 0.3631
Epoch 49/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3044 - accuracy: 0.3668 - val_loss: 0.1517 - val_accuracy: 0.3631
Epoch 50/100
42/42 [==============================] - 0s 4ms/step - loss: 0.2981 - accuracy: 0.3668 - val_loss: 0.1511 - val_accuracy: 0.3631
Epoch 51/100
42/42 [==============================] - 0s 4ms/step - loss: 0.2989 - accuracy: 0.3668 - val_loss: 0.1506 - val_accuracy: 0.3631
Epoch 52/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3025 - accuracy: 0.3668 - val_loss: 0.1502 - val_accuracy: 0.3631
Epoch 53/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3088 - accuracy: 0.3668 - val_loss: 0.1499 - val_accuracy: 0.3631
Epoch 54/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3006 - accuracy: 0.3668 - val_loss: 0.1495 - val_accuracy: 0.3631
Epoch 55/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3106 - accuracy: 0.3668 - val_loss: 0.1493 - val_accuracy: 0.3631
Epoch 56/100
42/42 [==============================] - 0s 2ms/step - loss: 0.2942 - accuracy: 0.3668 - val_loss: 0.1488 - val_accuracy: 0.3631
Epoch 57/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3315 - accuracy: 0.3668 - val_loss: 0.1491 - val_accuracy: 0.3631
Epoch 58/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3023 - accuracy: 0.3668 - val_loss: 0.1488 - val_accuracy: 0.3631

Epoch 59/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2996 - accuracy: 0.3668 - val_loss: 0.1484 - val_accuracy: 0.3631
Epoch 60/100
42/42 [==============================] - 0s 2ms/step - loss: 0.3023 - accuracy: 0.3668 - val_loss: 0.1480 - val_accuracy: 0.3631
Epoch 61/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3077 - accuracy: 0.3668 - val_loss: 0.1479 - val_accuracy: 0.3631
Epoch 62/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3077 - accuracy: 0.3668 - val_loss: 0.1477 - val_accuracy: 0.3631
Epoch 63/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3087 - accuracy: 0.3668 - val_loss: 0.1476 - val_accuracy: 0.3631
Epoch 64/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3077 - accuracy: 0.3668 - val_loss: 0.1474 - val_accuracy: 0.3631
Epoch 65/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3141 - accuracy: 0.3668 - val_loss: 0.1474 - val_accuracy: 0.3631
Epoch 66/100
42/42 [==============================] - 0s 4ms/step - loss: 0.2856 - accuracy: 0.3668 - val_loss: 0.1468 - val_accuracy: 0.3631
Epoch 67/100
42/42 [==============================] - 0s 4ms/step - loss: 0.2846 - accuracy: 0.3668 - val_loss: 0.1461 - val_accuracy: 0.3631
Epoch 68/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3012 - accuracy: 0.3668 - val_loss: 0.1459 - val_accuracy: 0.3631
Epoch 69/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3012 - accuracy: 0.3668 - val_loss: 0.1456 - val_accuracy: 0.3631
Epoch 70/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2891 - accuracy: 0.3668 - val_loss: 0.1452 - val_accuracy: 0.3631
Epoch 71/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3039 - accuracy: 0.3668 - val_loss: 0.1450 - val_accuracy: 0.3631
Epoch 72/100
42/42 [==============================] - 0s 4ms/step - loss: 0.2908 - accuracy: 0.3668 - val_loss: 0.1446 - val_accuracy: 0.3631
Epoch 73/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3020 - accuracy: 0.3668 - val_loss: 0.1445 - val_accuracy: 0.3631
Epoch 74/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3039 - accuracy: 0.3668 - val_loss: 0.1444 - val_accuracy: 0.3631
Epoch 75/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3114 - accuracy: 0.3668 - val_loss: 0.1444 - val_accuracy: 0.3631
Epoch 76/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3020 - accuracy: 0.3668 - val_loss: 0.1443 - val_accuracy: 0.3631
Epoch 77/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2945 - accuracy: 0.3668 - val_loss: 0.1440 - val_accuracy: 0.3631
Epoch 78/100
42/42 [==============================] - 0s 2ms/step - loss: 0.3076 - accuracy: 0.3668 - val_loss: 0.1440 - val_accuracy: 0.3631
Epoch 79/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2954 - accuracy: 0.3668 - val_loss: 0.1438 - val_accuracy: 0.3631
Epoch 80/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3039 - accuracy: 0.3668 - val_loss: 0.1437 - val_accuracy: 0.3631
Epoch 81/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3142 - accuracy: 0.3668 - val_loss: 0.1438 - val_accuracy: 0.3631
Epoch 82/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3095 - accuracy: 0.3668 - val_loss: 0.1439 - val_accuracy: 0.3631
Epoch 83/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3142 - accuracy: 0.3668 - val_loss: 0.1440 - val_accuracy: 0.3631
Epoch 84/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3301 - accuracy: 0.3668 - val_loss: 0.1446 - val_accuracy: 0.3631
Epoch 85/100
42/42 [==============================] - 0s 5ms/step - loss: 0.3039 - accuracy: 0.3668 - val_loss: 0.1445 - val_accuracy: 0.3631
Epoch 86/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3095 - accuracy: 0.3668 - val_loss: 0.1445 - val_accuracy: 0.3631
Epoch 87/100
42/42 [==============================] - 0s 4ms/step - loss: 0.2992 - accuracy: 0.3668 - val_loss: 0.1443 - val_accuracy: 0.3631
Epoch 88/100
42/42 [==============================] - 0s 5ms/step - loss: 0.2992 - accuracy: 0.3668 - val_loss: 0.1441 - val_accuracy: 0.3631
Epoch 89/100
42/42 [==============================] - 0s 3ms/step - loss: 0.3114 - accuracy: 0.3668 - val_loss: 0.1442 - val_accuracy: 0.3631
Epoch 90/100
42/42 [==============================] - 0s 3ms/step - loss: 0.2983 - accuracy: 0.3668 - val_loss: 0.1439 - val_accuracy: 0.3631
Epoch 91/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3076 - accuracy: 0.3668 - val_loss: 0.1439 - val_accuracy: 0.3631
Epoch 92/100
42/42 [==============================] - 0s 5ms/step - loss: 0.2851 - accuracy: 0.3668 - val_loss: 0.1434 - val_accuracy: 0.3631
Epoch 93/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3180 - accuracy: 0.3668 - val_loss: 0.1437 - val_accuracy: 0.3631
Epoch 94/100
42/42 [==============================] - 0s 5ms/step - loss: 0.3076 - accuracy: 0.3668 - val_loss: 0.1437 - val_accuracy: 0.3631
Epoch 95/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3067 - accuracy: 0.3668 - val_loss: 0.1437 - val_accuracy: 0.3631
Epoch 96/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3076 - accuracy: 0.3668 - val_loss: 0.1437 - val_accuracy: 0.3631
Epoch 97/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3208 - accuracy: 0.3668 - val_loss: 0.1439 - val_accuracy: 0.3631
Epoch 98/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3011 - accuracy: 0.3668 - val_loss: 0.1438 - val_accuracy: 0.3631
Epoch 99/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3105 - accuracy: 0.3668 - val_loss: 0.1438 - val_accuracy: 0.3631
Epoch 100/100
42/42 [==============================] - 0s 4ms/step - loss: 0.3227 - accuracy: 0.3668 - val_loss: 0.1441 - val_accuracy: 0.3631

In [107]:
training_score = model.evaluate(training_features,training_labels)
print("\n Training Accuracy:", training_score[1])

42/42 [==============================] - 0s 2ms/step - loss: 0.1548 - accuracy: 0.3668

 Training Accuracy: 0.36684170365333557

In [109]:
testing_score = model.evaluate(testing_features,testing_labels)
print("\n Testing Accuracy:", testing_score[1])

42/42 [==============================] - 0s 2ms/step - loss: 0.1441 - accuracy: 0.3631

 Testing Accuracy: 0.36309078335762024

Prediction Model Accuracy

In [135]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.20.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\rajan\anaconda3\lib\site-packages (from mlxtend) (3.5.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\rajan\anaconda3\lib\site-packages (from mlxtend) (1.7.3)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\rajan\anaconda3\lib\site-packages (from mlxtend) (1.0.2)
Requirement already satisfied: setuptools in c:\users\rajan\anaconda3\lib\site-packages (from mlxtend) (61.2.0)
Requirement already satisfied: pandas>=0.24.2 in c:\users\rajan\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\rajan\anaconda3\lib\site-packages (from mlxtend) (1.1.0)
Requirement already satisfied: numpy>=1.16.2 in c:\users\rajan\anaconda3\lib\site-packages (from mlxtend) (1.22.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\rajan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.0.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rajan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: cycler>=0.10 in c:\users\rajan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\rajan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rajan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\rajan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\rajan\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\rajan\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\rajan\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\rajan\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.20.0
Note: you may need to restart the kernel to use updated packages.

In [137]:
from mlxtend.evaluate import scoring

In [152]:
y_targ = training
y_pred = testing
res = scoring(y_target=y_targ, y_predicted=y_pred, metric='accuracy')

print('accuracy: %s%%' % (res * 1))

accuracy: 0.21780445111277819%